version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/anoush/app/node_modules
      - .:/home/anoush/app  
  tests:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - /home/anoush/app/node_modules
      - .:/home/anoush/app

    command: ["npm", "run", "test"]  
